### ISSUE TITLE
Mark homework 1, exercise 3 of Jonathan-Badger

### ISSUE THREAD

**Issue by jbadger3** [jbadger3/stat679work#3]
@cecileane
# HW1: Exercise 3
- Directories for hw1 were updated and reorganized with the addition of scripts/ and results/. 
- Corresponding files were moved into the new directories.
- A new script `detailed_summary.sh` was created for exercise 3, but corrected to an updated version of `summarizeSNaQres.sh`
- A nested .git repo and a number of other damaging errors were detected, so please use the final v1.2.3 for grading

f3004c6747022fee62a91d41c656ae7a1b3c9d21

**Comment by anqis929** [comment]
Hi Jonathan @jbadger3 @cecileane , 
Very Good Job! 
You smartly used  many "grep" "basename" "sed" and "cut" commands. These commands are quit useful and they are the main learning objectives in the past two weeks.  So it is great that you know how to use these commands to extract things. 
But there are some minor things come up when I bash your script. 
So the code you used to grep CPU time " cpuTime=$(grep -i 'Elapsed time' "hw1-snaqTimeTests/out/$trimmed_name" | grep -Eo '\d+\.\d+') ", it should be working under your terminal but since I have different folder names than yours, so the path you used does not exist on my side. This prevents me from running through your code without changing the path in your code. You could consider using a relative path or save the relative path in a new variable.  This problem happened in other parts of the code, too. 
Also the code you used to grep number of fails, the code you provided returns 10 for each file, but the truth is some files have 100 failures, some have 25, some have 50. 

Otherwise, everything seems great! Great work!

Irene

**Comment by kunchieh** [comment]
Hi Jonathan @jbadger3 @cecileane 
You did a good job of presenting all useful tools that we learned in class. But there are few minor things that I want to mentioned.
First, you did a good job that giving a command on the top of the script telling the user that where the output file goes, and it would be better if you give an additional line describing what's in the file, i.e. analysis, h, CPU time, etc. 
Next, is as mentioned in the previous comments that not every folder is names as "hw1-snaqTimeTests". Nevertheless, I believe that every analysis will have both "out" and "log" documents. So what I would recommend is changing "hw1-snaqTimeTests/out/$trimmed_name" into out/$trimmed_name and run the script inside the folder hw1-snapTimeTests.
The last thing is a little style suggestion. Your f_abs, f_rel, x_abs are doing the same thing. You might want to do 

 #get "ftolAbs", "ftolRel", "xtolAbs" in the log file 
f_abs=$(grep "ftolAbs" $filename | cut -d, -f2 | cut -d= -f2)
f_rel=$(grep "ftolAbs" $filename | cut -d, -f2 | cut -d= -f2)
x_abs=$(grep "xtolAbs" $filename | cut -d= -f2 | cut -d, -f1)

which will help the reader or even future modifier.

Overall, you did a really good work.

Jason

**Comment by jbadger3** [comment]
Thanks for the feedback guys!  I will try and fix things next time using relative paths that follow the directory structure shared by ALL users.  I'll also look at implementing some kind of error checking as it was pointed out my 'number of fails' column is not gathering the correct data.

**Comment by cecileane** [comment]
Your comment points to a small bug in fact: in `f_rel=$(grep "ftolAbs" $filename | cut -d, -f2 | cut -d= -f2)`. It look likes if should be `ftolRel` instead of `ftolAbs` here (line 36 of file `detailed_summary.sh`).

**Comment by jbadger3** [comment]
Professor Ane, good catch!  After making the change in line 36 I'm getting the correct output!
