### ISSUE TITLE
Mark homework 2 Jonathan-Badger

### ISSUE THREAD

**Issue by jbadger3** [jbadger3/stat679work#4]
@cecileane 

Homework 2 has been completed and is ready for grading
- please read the readme.md file for instructions
- sample files are located in data/
- basic usage is
` ./merge_temp_energy_data.py -files temp_file energy_file`
- you can use -h to see help and additional options

https://github.com/jbadger3/stat679work/commit/ae7acf70ce2720cf97cf8a6f991f3833fb23fe3b

**Comment by cecileane** [comment]
Hi Jonathan,

Very nice job! Your work was easy to go through, and your script worked. More details below.

## overall presentation

You have a fantastic manual (readme) to use your script. You made excellent use of markdown style. There was a small typo in the name of the script, but easy to figure out.

## running your script

Great use of the argparse module to it easy to provide arguments, and get help on them. Your script ran smoothly. The header line should have kept the quotes that were present in the original temperature csv file, however, because there were commas present in individual cells. By removing the quotes, these commas are interpreted as creating new columns. I got a header like this:

    #,Date Time, GMT-05:00,K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe),,Energy Produced (KWh)

instead of something like this, which would correctly understand that there are only 4 columns:

    #,"Date Time, GMT-05:00","K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe)",energy (kWh)

Also, the last energy value did not get printed. I was expecting this (around line 350 in the merged data file):

    349,08/12/16 10:26:34 PM,70.02,
    350,08/12/16 11:26:34 PM,71.46,8.778
    351,08/13/16 12:26:34 AM,71.13,

but I got this after running your script, on those particular lines:

    349,08/12/16 10:26:34 PM,70.02,
    350,08/12/16 11:26:34 PM,71.46,
    351,08/13/16 12:26:34 AM,71.13,

All other energy values were there, on the correct lines.

## about your code

You included tests of your module, to check the function that parses lines in the energy files in particular. That's awesome. You have the documentation about the usage in a docstring for the module, and detailed documentation (with docstrings) for each individual function, where you list assumptions and give examples, that's really great too.

You broke the problem down into separate functions, that's great. You could have embedded your code to parse arguments into a function too, which would have made it possible to import your module as a library (I got an error when I tried). But small thing.

Great use of the DOTALL flag in a regular expression! I believe it was to remove quotes in the header line, that would be best to keep, but you learned one more thing along the way :)
Your variable names are well chosen: I found it easy to understand your code. Thanks!
